### ISSUE TITLE
Investigate fingertips API for PHE data

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-disability#19]
Data for PHE published statistics should be available via the [fingertips API](https://fingertips.phe.org.uk/api).

Currently, we're starting at a "landing page" of https://fingertips.phe.org.uk/profile-group/mental-health/profile/drugsandmentalhealth, clicking on the big "start" button, then selecting the "download" tab and then clicking "Data for County & UA (pre 4/19)" to download the data as CSV.

We want to discover whether the same data is available through fingertips and how to get at it, its metadata and possibly also the reference data, such that we can create a generic pipeline to transform data into data cubes.

If we can use fingertips directly for the data and metadata, it would preclude having to write a PHE scraper (GSS-Cogs/gss-utils#13), unblock GSS-Cogs/family-disability#8 and https://github.com/GSS-Cogs/PHE-Local-Alcohol-Profiles-for-England and also help refactor the other PHE based datasets.

**Comment by ajtucker** [comment]
For #8, after installing `fingertips_py`, we can do something like:

```
import fingertips_py as ftp
profile = ftp.get_profile_by_name('Co-occurring substance misuse and mental health issues')
ftp.get_metadata_for_profile_as_dataframe(profile['Id'])
```

This (in a Jupyter notebook) provides a list (table) of "indicators" and their definitions, such as: 

Indicator ID | Indicator | Definition | Rationale | Data source | Indicator production | Indicator source | Methodology | Standard population/values | Confidence interval details | ... | Notes | Frequency | Rounding | Data quality | Indicator Content | Specific rationale | Unit | Value type | Year type | Polarity
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
91872 | Deprivation score (IMD 2015) | The English Indices of Deprivation 2015 use 37... | Deprivation covers a broad range of issues and... | Department of Communities and Local Government... | The indices have been contructed by Oxford Con... | https://www.gov.uk/government/statistics/engli... | The English Indices of Deprivation 2015 are me... | NaN | NaN | ... | The Indices of Deprivation 2015 are relative m... | NaN | NaN | NaN | NaN | NaN | NaN | Score | Calendar | Not applicable
1730 | Percentage people living in 20% most deprived ... | % of the relevant population in this area

If we compare this to the CSV data download from above, we can see that the indicator ID and indicator names are the same: the first 100 or so lines are about Deprivation Score (IMD 2015), with ID 91872.

Next, we can use the fingertips API to grab the data directly for each indicator, e.g.:
```
ftp.get_data_for_indicator_at_all_available_geographies(91872)
```

However, it looks as though this data is much more fine grained than that downloaded via CSV, so next we need to figure out how it corresponds to the CSV data and how to just get the more granular data (county and unitary authority?).

**Comment by ajtucker** [comment]
Looking more closely, the "county and unitary authority" area ID is `102` (found both by looking at `https://fingertips.phe.org.uk/api/area_types?profile_ids=%5B91872%5D` and also by inspecting the URL of the download data page, https://fingertips.phe.org.uk/profile-group/mental-health/profile/drugsandmentalhealth/data#page/9/gid/1938132935/pat/6/par/E12000004/ati/102/are/E06000015).

The data can be fetched directly using:
```
ftp.get_all_data_for_profile(profile['Id'], area_type_id=[102])
```

This gives back a table of 88,100 rows and looks really similar to the CSV you get when you download the "Data for County & UA (pre 4/19)" link, although this is 79,501 rows.

**Comment by ajtucker** [comment]
The next questions are: how should indicators, profiles, domains, areas, groups, etc. etc. map to data cubes, and can we get dimension labels and concept schemes out?

**Comment by mikeAdamss** [comment]
so we _can_ pull the data off the fingertips API but there's a lot of questions around what to take and how we want to shape that data. And until we answer those questions this ones a bit of  fuzzy task in terms of getting it to "done".

I'm treating [family-disability/issues/8](https://github.com/GSS-Cogs/family-disability/issues/8) as the spike into practicalities. If (and it's a big if) it ends up generating something we're happy with, then a generic "get fingertips datasets" pipeline should be easy enough, the info is all there.

I'm going to include more details on indicators/domains etc there, as it's on ongoing discussion. However, is should end up as a "one size fits all" approach. So the transform logic for the /drugsAndMentalHealth profile should apply equally to the others.

For consideration - since the fingertips identifiers are rationalised within the fingertips eco-system, I'd also consider removing it from the other dataset families so we can just build a lift and shift pipeline to pull it all across en masse. Definitely possible, but again, highly dependent on getting a result we're happy with from the spike.

**Comment by mikeAdamss** [comment]
@ajtucker - closing this as it's too wrapped up in the other to really be it's own card anymore.
